default_model: gpt-3.5-turbo
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: deepseek-r1
    litellm_params:
      model: ollama/deepseek-r1:14b
      api_base: http://host.docker.internal:11434
