name: Lint

env:
  NODE_VERSION: "22.14.0"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Frontend Lint & Prettier check
        working-directory: frontend
        run: npm run lint
