name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Update npm to latest
        run: npm install -g npm@latest
        working-directory: frontend

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Frontend Lint & Prettier check
        working-directory: frontend
        run: npm run lint

      - name: Setup Java (Oracle)
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '23'

      - name: Backend Lint check
        working-directory: backend
        run: ./gradlew check
