name: Tests

env:
  JAVA_VERSION: '23.0.2'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java (Oracle)
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Backend Tests
        working-directory: backend
        run: ./gradlew check
