name: Tests

env:
  JAVA_VERSION: "23.0.2"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java (Oracle)
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "gradle"
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - name: Backend Tests
        run: ./gradlew check
